### ISSUE TITLE
Error-prone amount comparison

### ISSUE THREAD

**Issue by bitfag** [xeroc/python-graphenelib#101]
To compare amounts asset comparison performed prior (assert):

```python
    def __eq__(self, other):
        if isinstance(other, Amount):
            assert other["asset"] == self["asset"]
            return self["amount"] == other["amount"]
```

This means full dictionary comparison is happening, as `self["asset"]` is dict with asset data. If any asset data changed between `Amount`s instantiation, this will lead to error:

```python
a = Amount('10 CNY')
b = Amount('10 CNY')
a['asset']['options']['core_exchange_rate']['base']['amount'] += 1
a == b
```

The solution is to compare only asset ids:
`assert other["asset"]["id"] == self["asset"]["id"]`

**Comment by xeroc** [comment]
good idea, can you provide a simple pullrequest to conpare self["asset"]["id"] instead?

**Comment by bitfag** [comment]
Ok, I'll prepare a PR.
