### ISSUE TITLE
Idea: split data structures from data loaders

### ISSUE THREAD

**Issue by bitphage** [xeroc/python-graphenelib#104]
Current classes (Asset, Amount, Price, etc) are responsible both for loading data via API and storing/handling this data (copy, multiplication, division, comparison etc)

The idea is to split data loading and data storing/processing to separate classes. One class is for loading object, and second to store object data and doing all data processing. This is needed to avoid loading of blockchain objects via API when instantiating new classes in various methods like `__mul__`, `__div__` etc. This is important as it's almost impossible to make asyncio versions of magic methods. In new design magic methods are operate only on data storage classes without need to query API.

Here is the brief demonstration:

```python
from asyncinit import asyncinit

class Data(dict):
    """ Actual data is stored here
    """
    def __init__(self, obj):
        # Do all usual things to load data into attributes etc
        self['foo'] = obj['foo']
        
    def copy():
        pass
    
    def __mul__():
        pass
    
    def __div__():
        pass
        
class Proxy(Data):
    """ Amount, Asset, Price, etc
    """
    def __init__(self, a):
        obj = self.load_data(a)
        self.__data = Data(obj)
    
    def load_data(self, o):
        """ RPC call here
        """
        return {'foo': 'bar'}
    
    def __getattr__(self, name):
        return getattr(self.__data, name)
    
@asyncinit
class ProxyAio(Proxy):
    """ Example async loader
    """
    async def __init__(self, a):
        obj = await self.load_data(a)
        self.__data = Data(obj)
    
    async def load_data(self, o):
        """ RPC call here
        """
        return {'foo': 'bar'}
```

**Comment by bitfag** [comment]
I did test implementation of this concept for Asset class with refactoring of blockchainobject.py to avoid  loading via `self.refresh()`.

**Comment by xeroc** [comment]
Good call .. I like that idea. It always bothered me that the classes mix up functionalities in a weird way.
