### ISSUE TITLE
Modules docs

### ISSUE THREAD

**Issue by bitfag** [xeroc/python-graphenelib#134]
For each module there is file like `graphenebase.memo.rst`. I suggest to auto-generate such files via sphinxcontrib-apidoc module, would you not mind if I add this into my further PR?

**Comment by xeroc** [comment]
https://github.com/xeroc/python-graphenelib/blob/master/Makefile#L45

The makefile also has a `release` that runs through semversioner for automatically pushing verison number and providing a CHANGELOG.

**Comment by bitfag** [comment]
@xeroc how does semversioner solves generating **documentation**? This:

```
graphenecommon.vesting module
=============================

.. automodule:: graphenecommon.vesting
    :members:
    :undoc-members:
    :show-inheritance:
```

I say this could be autogenerated.

**Comment by xeroc** [comment]
In the Makefile:

```
docs:
        sphinx-apidoc -d 6 -e -f -o docs . *.py tests
        # or SPHINX_APIDOC_OPTIONS="members,undoc-members,show-inheritance,inherited-members" sphinx-apidoc -d 6 -e -f -o docs . *.py tests
        make -C docs clean html
```

For `make release`:
```
prerelease: test docs docs_store authors authors_store
release: prerelease semver clean build check dist upload git
```

**Comment by bitfag** [comment]
Oh I didn't noticed `sphinx-apidoc` call from Makefile, thanks. :man_facepalming:
