### ISSUE TITLE
trade type issue in returnTradeHistory() method

### ISSUE THREAD

**Issue by bitcrab** [xeroc/python-graphenelib#45]
below is the return when I call returnTradeHistory("CNY_BTS") as account trans.bot
"CNY_BTS": [
        {
            "amount": 28.4,
            "rate": 35.21126760563381,
            "total": 1000.0000000000001,
            "date": "2016-07-09T06:40:18",
            "type": "buy"
        },
        {
            "amount": 0.292,
            "rate": 34.36229452054795,
            "total": 10.03379,
            "date": "2016-07-09T06:38:24",
            "type": "sell"
        }]

actually in both trade trans.bot pay CNY and receive BTS, the difference is that in the first trade(the top one) trans.bot trade as a maker, and in the second trade a taker, I check exchange.py and found the source data define "buy" or "sell" with the perspective of the taker.

so that means returnTradeHistory need not only check with "if f["op"]["pays"]["asset_id"] == m["base"] :",  but also need to check whether f["op"]["account_id"] equal to the caller. and then can get the right trade type.

BTW, I found returnTradeHistory("BTS_CNY") does not work, possible to make this work?

**Comment by xeroc** [comment]
Thanks for the Pullrequest

PR: https://github.com/xeroc/python-graphenelib/pull/46

I have added some comments there and am closing this issue..
