### ISSUE TITLE
piston command not working

### ISSUE THREAD

**Issue by kadnan** [xeroc/python-graphenelib#48]
I am now getting error:

```
The 'websockets==2.0' distribution was not found and is required by steem
```

Infact it's already there

```
aconda3/anaconda/lib/python3.5/site-packages
Requirement already satisfied (use --upgrade to upgrade): asyncio in /anaconda3/anaconda/lib/python3.5/site-packages (from websockets==2.0)
```

**Comment by xeroc** [comment]
try

`pip3 install -r requirements-web.txt --upgrade`

not sure, but you may need to add `--user` aswell .. if it fails with permissions error

**Comment by kadnan** [comment]
>pip3 install -r requirements-web.txt --upgrade

Where's the requirement file?

**Comment by xeroc** [comment]
it's in the piston repository .. where this issue should be aswell .. https://github.com/xeroc/piston.
