### ISSUE TITLE
Fix JSON Decode Error

### ISSUE THREAD

**Issue by pmartynov** [xeroc/python-graphenelib#51]
I've just tried follow() functionality in Piston which calls custom_json, which passes required_posting_auths, which is an Array of Strings, which causes `json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)` because it eventually tries to make JsonObj out of String

The fix is in https://github.com/xeroc/python-graphenelib/pull/50

**Comment by xeroc** [comment]
Sorry about this, I had the corresponding fix in python-grapehen (develop) but missed to release it and fix the dependency .. will do so shortly
