### ISSUE TITLE
issue in deep_eq

### ISSUE THREAD

**Issue by bitcrab** [xeroc/python-graphenelib#52]
some data element are not in correct format while comparing, in the screenshot, while compare transactions, in the data got from block the min_to_receive['amount'] should be int but actually it is string, and the result is that when you submit an order with returnID=True but  you cannot got the orderid

<img width="688" alt="screenshot from 2016-12-13 21_37_07" src="https://cloud.githubusercontent.com/assets/5886543/21144511/f0232c72-c185-11e6-8e4e-cee3b2c85891.png">

**Comment by xeroc** [comment]
Oha .. those backend issues with int vs. string drive me crazy ..
any recommendations on how to fix this?
