### ISSUE TITLE
Certificate validation is disabled for wss urls

### ISSUE THREAD

**Issue by zbuc** [xeroc/python-graphenelib#60]
https://github.com/xeroc/python-graphenelib/blob/master/grapheneapi/graphenewsrpc.py#L78

This disables certificate validation for secure (`wss://`) endpoints, rendering them useless at protecting against a man-in-the-middle attacker.

This is a high severity bug for a project such as this that people may be using to manage their assets.

**Comment by zbuc** [comment]
Hi,

Is there any update available on this?

This is a serious security issue for an API library and it's concerning that there's been no reply for twenty days.

**Comment by xeroc** [comment]
Thank you, I pushed a fix
