### ISSUE TITLE
Account Create and TESTNET

### ISSUE THREAD

**Issue by sschiessl-bcp** [xeroc/python-graphenelib#77]
When adding 
```
operations.Account_create(**op)
```
that contains a prefix flag into ProposalBuilder, it gets recreated when broadcasting (through `self.constructTx()` in TransactionBuilder), but at that point without the prefix, leading to fallback to "BTS" as prefix

**Comment by sschiessl-bcp** [comment]
Workaround: 
Set `bitsharesbase.objects.default_prefix = bitshares_instance.prefix` before broadcasting

**Comment by xeroc** [comment]
Closing ..
wrong repo.
corresponding fix in https://github.com/bitshares/python-bitshares/commit/ba23069d9b946d1a9ef238b9db12ae41a0a835de
