### ISSUE TITLE
Bitshares specifics in Blockchain.ops()

### ISSUE THREAD

**Issue by bitfag** [xeroc/python-graphenelib#79]
```python
                    # Replace opid by op name
                    op[0] = self.operationids.getOperationNameForId(op[0])
```

This is bitshares-specific as another graphene chains may already have op name here.

**Comment by xeroc** [comment]
self operationids is actually a `module` as you can see here:
https://github.com/bitshares/python-bitshares/blob/master/bitshares/blockchain.py#L25

I guess you problem is with the name `getOperatioNameForId` while the content of `op[0]` could be a an operation name already.

Do you have a proposal on how to resolve this nicely?

**Comment by bitfag** [comment]
Yes exactly, I'm getting operation name in `op[0]` so no translation is needed.

Something like this?

```python
op[0] = self.operationids.getOperationNameForId(op[0]) if isinstance(op[0], int) else op[0]
```

**Comment by xeroc** [comment]
Hope this solution solves your issue
