### ISSUE TITLE
Bitshares specifics in TransactionBuilder constructTx()

### ISSUE THREAD

**Issue by bitfag** [xeroc/python-graphenelib#80]
`ops = self.add_required_fees(ops, asset_id=self.fee_asset_id)`

This is bitshares specific as another graphene chains may not have "fee" in operations.

**Comment by xeroc** [comment]
Just replace add_required_fees with:
```python
def add_required_fees(self, ops, **kwargs):
    return ops
```

**Comment by bitfag** [comment]
Oh thanks, this is so obvious :man_facepalming:
